### ISSUE TITLE
[question] new URL(...).origin === "null" for unknown/custom schemes (not this module but browser/node)

### ISSUE THREAD

**Issue by vladimiry** [cliqz/url-parser#397]
In node/browser when native URL used the call like this `new URL("webclient://domain.net/blank.html?loader-id=2fb1c580").origin` returns "null" (notice unknowns/custom scheme). This library returns the value regardless the scheme and I like such behavior.

The questions:
- Is this module planning returning "null" for unknown/custom schemes like node & browser do?
- Maybe there is a link to documentation which covers the described "null" case?

**Comment by sammacbeth** [comment]
Thanks for this. This is a diversion from the URL Spec that we should document in the project.

A `'null'` origin is an 'opaque origin' as described in the [URL Standard](https://url.spec.whatwg.org/#origin). We currently only return this when the URL has no authority, while the standard will return an opaque origin for URL schemes not in a set of known protocols.

Note that the set of schemes that return an origin is inconsistent across URL implementations. Browser implementations will include custom protocols that behave like HTTP. For example on Firefox:
```javascript
new URL('moz-extension://test/index.html').origin // = "moz-extension://test"
new URL('chrome-extension://test/index.html').origin // = "null"
```
Run these two lines in Chrome, and you get different results.

At the moment this library is agnostic to URL protocols, so it will generate an origin for any URL with a valid authority. Do you have a use-case for the exact origin behaviour from the spec?

**Comment by vladimiry** [comment]
Thanks for the detailed response.

> Do you have a use-case for the exact origin behaviour from the spec?

Nope. I mentioned I like how the library currently behaves in terms of origin resolving. I can whitelist/"null" the origins in my own if needed.

> At the moment this library is agnostic to URL protocols, so it will generate an origin for any URL with a valid authority.

If one day the library will have changed this behavior please bump major version.
